export function initGames(games, specialGameButtons) {
    // Special Game Button Functionality (Now accepting an array of buttons)
    specialGameButtons.forEach(button => {
        button.addEventListener('click', () => {
            const gameUrl = button.dataset.gameUrl;
            const gameName = button.dataset.gameName;

            if (gameUrl) {
                openGameInNewTab(gameName, gameUrl);
            }
        });
    });
}

export function openGameInNewTab(gameName, gameUrl) {
    // Load the game URL in an iframe within an about:blank tab
    // By writing directly to the document, we create a clean tab that
    // does not inherit the original page's scripts or styles, effectively
    // removing any pop-ups or UI elements from the cloaked tab.
    const newTab = window.open('about:blank', '_blank');
    if (newTab) {
        newTab.document.write(`
            <!DOCTYPE html>
            <html>
            <head>
                <title>Home</title> <!-- Set the new tab's title to "Home" -->
                <link rel="icon" href="https://upload.wikimedia.org/wikipedia/commons/5/59/Google_Classroom_Logo.png" type="image/png"> <!-- Add the favicon link -->
                <style>
                    body, html {
                        margin: 0;
                        padding: 0;
                        overflow: hidden;
                        height: 100%;
                        background-color: #000; /* Optional: Set background to black while loading iframe */
                    }
                    iframe {
                        width: 100%;
                        height: 100%;
                        border: none;
                        display: block; /* Ensure iframe takes up the full space */
                    }
                </style>
            </head>
            <body>
                <iframe src="${gameUrl}" allow="fullscreen; autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" allowfullscreen></iframe>
            </body>
            </html>
        `);
        newTab.document.close();
    } else {
        // Do nothing if popup is blocked, do not show an alert.
        // The browser's built-in popup blocker notification is sufficient.
    }
}

export const gameData = {
    'super smash bros.': 'https://k-web-topaz.vercel.app/games/supersmashbros/index.html',
    'pokemon emerald': 'https://k-web-topaz.vercel.app/games/pokemonemerald/index.html',
    'street fighter 2': 'https://k-web-topaz.vercel.app/games/streetfighter2/index.html',
    'mario kart 64': 'https://k-web-topaz.vercel.app/games/mariokart64/index.html',
    'cooking mama': 'https://k-web-topaz.vercel.app/games/cookingmama/index.html',
    'superstar saga': 'https://k-web-topaz.vercel.app/games/superstarSaga/index.html',
    'sonic advance 2': 'https://k-web-topaz.vercel.app/games/sonicadvance2/index.html',
    'spirit tracks': 'https://k-web-topaz.vercel.app/games/spirittracks/index.html',
    'kirby mass attack': 'https://k-web-topaz.vercel.app/games/kirbymassattack/index.html',
    'animal crossing wild world': 'https://k-web-topaz.vercel.app/games/animalcrossingwildworld/index.html',
    'super mario bros 3': 'https://k-web-topaz.vercel.app/games/supermariobros3/index.html',
    'slope': 'https://k-web-topaz.vercel.app/games/slope/index.html',
    'cookie clicker': 'https://k-web-topaz.vercel.app/games/cookieclicker/index.html',
    'crossy road': 'https://k-web-topaz.vercel.app/games/crossy/index.html',
    'friday night funkin\'': 'https://k-web-topaz.vercel.app/games/fnf/index.html',
    'skibidi toilet 1v100': 'https://k-web-topaz.vercel.app/games/skibidi1v100/index.html',
    'geometry dash': 'https://k-web-topaz.vercel.app/games/gdlite/index.html',
    'pizza tower': 'https://k-web-topaz.vercel.app/games/pizzatower/',
    'subway surfers': 'https://k-web-topaz.vercel.app/games/subwaysurfers/index.html',
    'flappy bird': 'https://k-web-topaz.vercel.app/games/flappy/index.html',
    'papas pizzaria': 'https://k-web-topaz.vercel.app/games/papaspizzaria/index.html',
    'papas burgeria': 'https://k-web-topaz.vercel.app/games/papasburgeria/index.html',
    'sm64': 'https://k-web-topaz.vercel.app/games/sm64/index.html',
    'run 3': 'https://k-web-topaz.vercel.app/games/run3/index.html',
    'bitlife': 'https://k-web-topaz.vercel.app/games/bitlife/index.html',
    'minecraft': 'https://k-web-topaz.vercel.app/games/mc/index.html',
    'temple run 2': 'https://k-web-topaz.vercel.app/games/templerun2/index.html',
    'duck life 4': 'https://k-web-topaz.vercel.app/games/ducklife4/index.html',
    'dino game': 'https://k-web-topaz.vercel.app/games/dinogame/index.html',
    'jetpack joyride': 'https://k-web-topaz.vercel.app/games/jetpackjoyride/index.html',
    'retro bowl': 'https://k-web-topaz.vercel.app/games/retrobowl/index.html',
    'fruit ninja': 'https://k-web-topaz.vercel.app/games/fruitninja/index.html',
    '2048': 'https://k-web-topaz.vercel.app/games/2048/index.html',
    'tetris': 'https://k-web-topaz.vercel.app/games/tetris/index.html',
    'fancy pants adventure': 'https://k-web-topaz.vercel.app/games/fancypantsadventure/index.html',
    'happy wheels': 'https://k-web-topaz.vercel.app/games/happywheels/index.html',
    'papas hot doggeria': 'https://k-web-topaz.vercel.app/games/papashotdoggeria/index.html',
    'paper io 2': 'https://k-web-topaz.vercel.app/games/paperio2/index.html',
    'superhot': 'https://k-web-topaz.vercel.app/games/superhot/index.html',
    'the binding of isaac': 'https://k-web-topaz.vercel.app/games/thebindingofisaac/index.html',
    'townscaper': 'https://k-web-topaz.vercel.app/games/townscaper/index.html',
    'tunnel rush': 'https://k-web-topaz.vercel.app/games/tunnelrush/index.html',
    'theme hotel': 'https://k-web-topaz.vercel.app/games/themehotel/index.html',
    'escaping the prison': 'https://k-web-topaz.vercel.app/games/escapingtheprison/index.html',
    'stealing the diamond': 'https://k-web-topaz.vercel.app/games/stealingthediamond/index.html',
    'infiltrating the airship': 'https://k-web-topaz.vercel.app/games/infiltratingtheairship/index.html',
    'fleeing the complex': 'https://k-web-topaz.vercel.app/games/fleeingthecomplex/index.html',
    'the impossible quiz': 'https://k-web-topaz.vercel.app/games/theimpossiblequiz/index.html',
    'solitaire': 'https://k-web-topaz.vercel.app/games/solitaire/index.html',
    'drift hunters': 'https://k-web-topaz.vercel.app/games/drifthunters/index.html',
    'vex 6': 'https://k-web-topaz.vercel.app/games/vex6/index.html',
    'among us': 'https://k-web-topaz.vercel.app/games/amongus/index.html',
    'surf': 'https://k-web-topaz.vercel.app/games/surf/index.html',
    'moto x3m': 'https://k-web-topaz.vercel.app/games/motox3m/index.html',
    'fnaf': 'https://k-web-topaz.vercel.app/games/fnaf/index.html',
    'fnaf 2': 'https://k-web-topaz.vercel.app/games/fnaf-2/index.html',
    'fnaf 3': 'https://k-web-topaz.vercel.app/games/fnaf-3/index.html',
    'fnaf 4': 'https://k-web-topaz.vercel.app/games/fnaf-4/index.html',
    'riddle school 1': 'https://k-web-topaz.vercel.app/games/riddleschool/riddleschool1/index.html',
    'riddle school 2': 'https://k-web-topaz.vercel.app/games/riddleschool/riddleschool2/index.html',
    'riddle school 3': 'https://k-web-topaz.vercel.app/games/riddleschool/riddleschool3/index.html',
    'riddle school 4': 'https://k-web-topaz.vercel.app/games/riddleschool/riddleschool4/index.html',
    'riddle school 5': 'https://k-web-topaz.vercel.app/games/riddleschool/riddleschool5/index.html',
    'riddle transfer': 'https://k-web-topaz.vercel.app/games/riddleschool/riddletransfer/index.html',
    'riddle transfer 2': 'https://k-web-topaz.vercel.app/games/riddleschool/riddletransfer2/index.html',
    'drift boss': 'https://k-web-topaz.vercel.app/games/driftboss/index.html',
    'pacman': 'https://k-web-topaz.vercel.app/games/pacman/index.html',
    'papas pancakeria': 'https://k-web-topaz.vercel.app/games/papaspancakeria/index.html',
    'rooftop': 'https://k-web-topaz.vercel.app/games/rooftop/index.html',
    'baldis basics': 'https://k-web-topaz.vercel.app/games/baldisbasics/index.html',
    'bob the robber 2': 'https://k-web-topaz.vercel.app/games/bobtherobber2/index.html',
    'minesweeper': 'https://k-web-topaz.vercel.app/games/minesweeper/index.html',
    'pokemon fire red': 'https://k-web-topaz.vercel.app/games/pokemonfirered/index.html',
    'super mario bros': 'https://k-web-topaz.vercel.app/games/supermariobros/index.html',
    'super mario kart': 'https://k-web-topaz.vercel.app/games/supermariokart/index.html',
    'super mario world': 'https://k-web-topaz.vercel.app/games/supermarioworld/index.html',
    'there is no game': 'https://k-web-topaz.vercel.app/games/thereisnogame/index.html',
    'worlds hardest game': 'https://k-web-topaz.vercel.app/games/worldshardestgame/index.html',
    'castlevania': 'https://k-web-topaz.vercel.app/games/castlevania/index.html',
    'donkey kong': 'https://k-web-topaz.vercel.app/games/donkeykong/index.html',
    'dr mario': 'https://k-web-topaz.vercel.app/games/drmario/index.html',
    'metroid': 'https://k-web-topaz.vercel.app/games/metroid/index.html',
    'super mario bros 2': 'https://k-web-topaz.vercel.app/games/supermariobros2/index.html',
    'the legend of zelda': 'https://k-web-topaz.vercel.app/games/thelegendofzelda/index.html',
    'warioware': 'https://k-web-topaz.vercel.app/games/warioware/index.html',
    'yoshis island': 'https://k-web-topaz.vercel.app/games/yoshisisland/index.html',
    'donkey kong land': 'https://k-web-topaz.vercel.app/games/donkeykongland/index.html',
    'kirbys dreamland': 'https://k-web-topaz.vercel.app/games/kirbysdreamland/index.html',
    'super mario land': 'https://k-web-topaz.vercel.app/games/supermarioland/index.html',
    'dogeminer': 'https://k-web-topaz.vercel.app/games/dogeminer/index.html',
    'tanuki sunset': 'https://k-web-topaz.vercel.app/games/tanukisunset/index.html',
    'aquapark slides': 'https://k-web-topaz.vercel.app/games/aquaparkslides/index.html',
    'color switch': 'https://k-web-topaz.vercel.app/games/colorswitch/index.html',
    'papas freezeria': 'https://k-web-topaz.vercel.app/games/papasfreezeria/index.html',
    'btd': 'https://k-web-topaz.vercel.app/games/btd/btd/index.html',
    'btd 2': 'https://k-web-topaz.vercel.app/games/btd/btd2/index.html',
    'btd 3': 'https://k-web-topaz.vercel.app/games/btd/btd3/index.html',
    'btd 4': 'https://k-web-topaz.vercel.app/games/btd/btd4/index.html',
    'bomberman': 'https://k-web-topaz.vercel.app/games/bomberman/index.html',
    'fire emblem': 'https://k-web-topaz.vercel.app/games/fireemblem/index.html',
    'ice climber': 'https://k-web-topaz.vercel.app/games/iceclimber/index.html',
    'mario kart super circuit': 'https://k-web-topaz.vercel.app/games/mariokartsupercircuit/index.html',
    'pokemon leaf green': 'https://k-web-topaz.vercel.app/games/pokemonleafgreen/index.html',
    'pokemon ruby': 'https://k-web-topaz.vercel.app/games/pokemonruby/index.html',
    'pokemon sapphire': 'https://k-web-topaz.vercel.app/games/pokemonsapphire/index.html',
    'adofai': 'https://k-web-topaz.vercel.app/games/adofai/index.html',
    'super smash flash': 'https://k-web-topaz.vercel.app/games/supersmashflash/index.html',
    'super meat boy': 'https://k-web-topaz.vercel.app/games/supermeatboy/index.html',
    'stickman hook': 'https://k-web-topaz.vercel.app/games/stickmanhook/index.html',
    'defend the tank': 'https://k-web-topaz.vercel.app/games/defendthetank/index.html',
    'sort the court': 'https://k-web-topaz.vercel.app/games/sortthecourt/index.html',
    'this is the only level': 'https://k-web-topaz.vercel.app/games/thisistheonlylevel/index.html',
    'run': 'https://k-web-topaz.vercel.app/games/run/index.html',
    'run 2': 'https://k-web-topaz.vercel.app/games/run2/index.html',
    'battleships': 'https://k-web-topaz.vercel.app/games/battleships/index.html',
    'breaking the bank': 'https://k-web-topaz.vercel.app/games/breakingthebank/index.html',
    'duck life': 'https://k-web-topaz.vercel.app/games/ducklife/index.html',
    'duck life 2': 'https://k-web-topaz.vercel.app/games/ducklife2/index.html',
    'duck life 3': 'https://k-web-topaz.vercel.app/games/ducklife3/index.html',
    'line rider': 'https://k-web-topaz.vercel.app/games/linerider/index.html',
    'mario combat': 'https://k-web-topaz.vercel.app/games/mariocombat/index.html',
    'raft wars 2': 'https://k-web-topaz.vercel.app/games/raftwars2/index.html',
    'space invaders': 'https://k-web-topaz.vercel.app/games/spaceinvaders/index.html',
    'mario kart ds': 'https://k-web-topaz.vercel.app/games/mariokartds/index.html',
    'new super mario bros': 'https://k-web-topaz.vercel.app/games/newsupermariobros/index.html',
    'nintendogs': 'https://k-web-topaz.vercel.app/games/nintendogs/index.html',
    'sm64 ds': 'https://k-web-topaz.vercel.app/games/sm64ds/index.html',
    'gun mayhem': 'https://k-web-topaz.vercel.app/games/gunmayhem/index.html',
    'learn to fly': 'https://k-web-topaz.vercel.app/games/learntofly/index.html',
    'rooftop 2': 'https://k-web-topaz.vercel.app/games/rooftop2/index.html',
    'fireboy and watergirl': 'https://k-web-topaz.vercel.app/games/fireboywatergirl/index.html',
    'chibi knight': 'https://k-web-topaz.vercel.app/games/chibiknight/index.html',
    'cluster rush': 'https://k-web-topaz.vercel.app/games/clusterrush/index.html',
    'doodle defender': 'https://k-web-topaz.vercel.app/games/doodledefender/index.html',
    'learn to fly 2': 'https://k-web-topaz.vercel.app/games/learntofly2/index.html',
    'papas scooperia': 'https://k-web-topaz.vercel.app/games/papasscooperia/index.html',
    'papas sushiria': 'https://k-web-topaz.vercel.app/games/papassushiria/index.html',
    'papas wingeria': 'https://k-web-topaz.vercel.app/games/papaswingeria/index.html',
    'raft wars': 'https://k-web-topaz.vercel.app/games/raftwars/index.html',
    'unfair mario': 'https://k-web-topaz.vercel.app/games/unfairmario/index.html',
    'boxing physics 2': 'https://k-web-topaz.vercel.app/games/boxingphysics2/index.html',
    'ace attorney': 'https://k-web-topaz.vercel.app/games/aceattorney/index.html',
    'metal gear solid': 'https://k-web-topaz.vercel.app/games/metalgearsolid/index.html',
    'mother 3': 'https://k-web-topaz.vercel.app/games/mother3/index.html',
    'pokemon diamond': 'https://k-web-topaz.vercel.app/games/pokemondiamond/index.html',
    'pokemon platinum': 'https://k-web-topaz.vercel.app/games/pokemonplatinum/index.html',
    'pokemon soulsilver': 'https://k-web-topaz.vercel.app/games/pokemonsoulsilver/index.html',
    'advance wars': 'https://k-web-topaz.vercel.app/games/advancewars/index.html',
    'banjo pilot': 'https://k-web-topaz.vercel.app/games/banjopilot/index.html',
    'super monkey ball jr': 'https://k-web-topaz.vercel.app/games/supermonkeyballjr/index.html',
    'the impossible quiz 2': 'https://k-web-topaz.vercel.app/games/theimpossiblequiz2/index.htm',
    'papas donuteria': 'https://k-web-topaz.vercel.app/games/papasdonuteria/index.html',
    'fancy pants adventure 2': 'https://k-web-topaz.vercel.app/games/fancypantsadventure2/index.html',
    'tiny fishing': 'https://k-web-topaz.vercel.app/games/tinyfishing/index.html',
    'big red button': 'https://k-web-topaz.vercel.app/games/bigredbutton/index.html',
    'achievement unlocked': 'https://k-web-topaz.vercel.app/games/achievementunlocked/index.html',
    'sonic advance': 'https://k-web-topaz.vercel.app/games/sonicadvance/index.html',
    'worms world party': 'https://k-web-topaz.vercel.app/games/wormsworldparty/index.html',
    'bad ice-cream': 'https://k-web-topaz.vercel.app/games/badicecream/index.html',
    'bad ice-cream 2': 'https://k-web-topaz.vercel.app/games/badicecream2/index.html',
    'bad ice-cream 3': 'https://k-web-topaz.vercel.app/games/badicecream3/index.html',
    'adventure capitalist': 'https://k-web-topaz.vercel.app/games/adventurecapitalist/index.html',
    'monkey mart': 'https://k-web-topaz.vercel.app/games/monkeymart/index.html',
    'doom 64': 'https://k-web-topaz.vercel.app/games/doom64/index.html',
    'banjo-kazooie': 'https://k-web-topaz.vercel.app/games/banjokazooie/index.html',
    'donkey kong 64': 'https://k-web-topaz.vercel.app/games/donkeykong64/index.html',
    'f-zero x': 'https://k-web-topaz.vercel.app/games/fzerox/index.html',
    'kirby 64': 'https://k-web-topaz.vercel.app/games/kirby64/index.html',
    'mario party': 'https://k-web-topaz.vercel.app/games/marioparty/index.html',
    'mario party 2': 'https://k-web-topaz.vercel.app/games/marioparty2/index.html',
    'ocarina of time': 'https://k-web-topaz.vercel.app/games/ocarinaoftime/index.html',
    'star fox 64': 'https://k-web-topaz.vercel.app/games/starfox64/index.html',
    'getaway shootout': 'https://k-web-topaz.vercel.app/games/getawayshootout/index.html',
    'rabbit samurai': 'https://k-web-topaz.vercel.app/games/rabbitsamurai/index.html',
    'mariopartyds': 'https://k-web-topaz.vercel.app/games/mariopartyds/index.html',
    'professor layton': 'https://k-web-topaz.vercel.app/games/professorlayton/index.html',
    'scribblenauts': 'https://k-web-topaz.vercel.app/games/scribblenauts/index.html',
    'advance wars 2': 'https://k-web-topaz.vercel.app/games/advancewars2/index.html',
    'harvest moon': 'https://k-web-topaz.vercel.app/games/harvestmoon/index.html',
    'mariotennis': 'https://k-web-topaz.vercel.app/games/mariotennis/index.html',
    'mega man zero': 'https://k-web-topaz.vercel.app/games/megamanzero/index.html',
    'super mario 64': 'https://k-web-topaz.vercel.app/games/sm64/index.html',
    'rocket soccer': 'https://k-web-topaz.vercel.app/games/rocketsoccer/index.html',
    'hole io': 'https://k-web-topaz.vercel.app/games/holeio/index.html',
    'legends of zelda: spirit tracks': 'https://k-web-topaz.vercel.app/games/spirittracks/index.html',
    'lazy jump 3d': 'https://k-web-topaz.vercel.app/games/lazyjump3d/index.html',
    'bad time simulator': 'https://k-web-topaz.vercel.app/games/badtimesimulator/index.html',
    'gun fest': 'https://k-web-topaz.vercel.app/games/gunfest/index.html',
    '10 minutes till dawn': 'https://k-web-topaz.vercel.app/games/10minutestilldawn/index.html',
    'pokemon stadium': 'https://k-web-topaz.vercel.app/games/pokemonstadium/index.html',
    'clicker heroes': 'https://k-web-topaz.vercel.app/games/clickerheroes/index.html',
    'redball 4': 'https://k-web-topaz.vercel.app/games/redball4/index.html',
    'pokemon mystery dungeon': 'https://k-web-topaz.vercel.app/games/pokemonmysterydungeon/index.html',
    'pokemon unbound': 'https://k-web-topaz.vercel.app/games/pokemonunbound/index.html',
    'papas cheeseria': 'https://k-web-topaz.vercel.app/games/papascheeseria/index.html',
    'papas cupcakeria': 'https://k-web-topaz.vercel.app/games/papascupcakeria/index.html',
    'papas bakeria': 'https://k-web-topaz.vercel.app/games/papasbakeria/index.html',
    'papas pastaria': 'https://k-web-topaz.vercel.app/games/papaspastaria/index.html',
    'gun mayhem 2': 'https://k-web-topaz.vercel.app/games/gunmayhem2/index.html',
    'gun mayhem redux': 'https://k-web-topaz.vercel.app/games/gunmayhemredux/index.html',
    'achievement unlocked 2': 'https://k-web-topaz.vercel.app/games/achievementunlocked2/index.html',
    'achievement unlocked 3': 'https://k-web-topaz.vercel.app/games/achievementunlocked3/index.html',
    'factory balls': 'https://k-web-topaz.vercel.app/games/factoryballs/index.html',
    'skywire': 'https://k-web-topaz.vercel.app/games/skywire/index.html',
    'super mario flash': 'https://k-web-topaz.vercel.app/games/supermarioflash/index.html',
    'golden sun': 'https://k-web-topaz.vercel.app/games/goldensun/index.html',
    'metroid fusion': 'https://k-web-topaz.vercel.app/games/metroidfusion/index.html',
    'dbz supersonic warriors': 'https://k-web-topaz.vercel.app/games/dbzsupersonicwarriors/index.html',
    'wario land 4': 'https://k-web-topaz.vercel.app/games/warioland4/index.html',
    'duck life 5': 'https://k-web-topaz.vercel.app/games/ducklife5/index.html',
    'learn to fly 3': 'https://k-web-topaz.vercel.app/games/learntofly3/index.html',
    'bloxors': 'https://k-web-topaz.vercel.app/games/bloxors/index.html',
    'electricman 2': 'https://k-web-topaz.vercel.app/games/electricman2/index.html',
    'portal': 'https://k-web-topaz.vercel.app/games/portal/index.html',
    'portal 2': 'https://k-web-topaz.vercel.app/games/portal2/index.html',
    'skywire 2': 'https://k-web-topaz.vercel.app/games/skywire2/index.html',
    'duck life 6': 'https://k-web-topaz.vercel.app/games/ducklife6/index.html',
    'boxing random': 'https://k-web-topaz.vercel.app/games/boxingrandom/index.html',
    'cell machine': 'https://k-web-topaz.vercel.app/games/cellmachine/index.html',
    'stickman boost': 'https://k-web-topaz.vercel.app/games/stickmanboost/index.html',
    'vex 3': 'https://k-web-topaz.vercel.app/games/vex3/index.html',
    'vex 4': 'https://k-web-topaz.vercel.app/games/vex4/index.html',
    'choose your weapon 2': 'https://k-web-topaz.vercel.app/games/chooseyourweapon2/index.html',
    'choose your weapon 3': 'https://k-web-topaz.vercel.app/games/chooseyourweapon3/index.html',
    'connect 4': 'https://k-web-topaz.vercel.app/games/connect4/index.html',
    'electric box': 'https://k-web-topaz.vercel.app/games/electricbox/index.html',
    'minecraft tower defence 2': 'https://k-web-topaz.vercel.app/games/mctowerdefence2/index.html',
    'cars 2': 'https://k-web-topaz.vercel.app/games/cars2/index.html',
    'cooking mama': 'https://k-web-topaz.vercel.app/games/cookingmama/index.html',
    'adventure time': 'https://k-web-topaz.vercel.app/games/adventuretime/index.html',
    'garfield gets real': 'https://k-web-topaz.vercel.app/games/garfieldgetsreal/index.html',
    'wario ware touched': 'https://k-web-topaz.vercel.app/games/wariowaretouched/index.html',
    'kirbypowerpaintbrush': 'https://k-web-topaz.vercel.app/games/kirbypowerpaintbrush/index.html',
    'sonic and knuckles': 'https://k-web-topaz.vercel.app/games/sonicandknuckles/index.html',
    'altered beast': 'https://k-web-topaz.vercel.app/games/alteredbeast/index.html',
    'sonic spinball': 'https://k-web-topaz.vercel.app/games/sonicspinball/index.html',
    'sonic the hedgehog 3': 'https://k-web-topaz.vercel.app/games/sonicthehedgehog3/index.html',
    'street so frage': 'https://k-web-topaz.vercel.app/games/streetsofrage/index.html',
    'golden axe': 'https://k-web-topaz.vercel.app/games/goldenaxe/index.html',
    'kirby amazing mirror': 'https://k-web-topaz.vercel.app/games/kirbyamazingmirror/index.html',
    'champion island': 'https://k-web-topaz.vercel.app/games/championisland/index.html',
    'supermario construct': 'https://k-web-topaz.vercel.app/games/supermarioconstruct/index.html',
    'clicker heroes': 'https://k-web-topaz.vercel.app/games/clickerheroes/index.html',
    'stairrace 3d': 'https://k-web-topaz.vercel.app/games/stairrace3d/index.html',
    'slope 2': 'https://k-web-topaz.vercel.app/games/slope2/index.html',
    'paperio 3d': 'https://k-web-topaz.vercel.app/games/paperio3d/index.html',
    'motoX3m spooky': 'https://k-web-topaz.vercel.app/games/motox3mspooky/index.html',
    'motoX3m winter': 'https://k-web-topaz.vercel.app/games/motox3mwinter/index.html',
    'papas tacomia': 'https://k-web-topaz.vercel.app/games/papastacomia/index.html',
    'ovo': 'https://k-web-topaz.vercel.app/games/ovo/index.html',
    'knife hit': 'https://k-web-topaz.vercel.app/games/knifehit/index.html',
    'burger and frights': 'https://k-web-topaz.vercel.app/games/burgerandfrights/index.html',
    'chess': 'https://k-web-topaz.vercel.app/games/chess/index.html',
    'fnf midfight': 'https://k-web-topaz.vercel.app/games/fnfmidfight/index.html',
    'thumb fighter': 'https://k-web-topaz.vercel.app/games/thumbfighter/index.html',
    'snow battle io': 'https://k-web-topaz.vercel.app/games/snowbattleio/index.html',
    'lazy jump 3d': 'https://k-web-topaz.vercel.app/games/lazyjump3d/index.html',
    'go ball': 'https://k-web-topaz.vercel.app/games/goball/index.html',
    'flippy fish': 'https://k-web-topaz.vercel.app/games/flippyfish/index.html',
    'shop empire': 'https://k-web-topaz.vercel.app/games/shopempire/index.html',
    'monster brawl': 'https://k-web-topaz.vercel.app/games/monsterbrawl/index.html',
    'multitask': 'https://k-web-topaz.vercel.app/games/multitask/index.html',
    'shift': 'https://k-web-topaz.vercel.app/games/shift/index.html',
    'shift 2': 'https://k-web-topaz.vercel.app/games/shift2/index.html',
    'shift 3': 'https://k-web-topaz.vercel.app/games/shift3/index.html',
    'shift4 ': 'https://k-web-topaz.vercel.app/games/shift4/index.html',
    'monopoly': 'https://k-web-topaz.vercel.app/games/monopoly/index.html',
    'picrossds': 'https://k-web-topaz.vercel.app/games/picrossds/index.html',
    'wario ware diy': 'https://k-web-topaz.vercel.app/games/wariowarediy/index.html',
    'pizza tower': 'https://k-web-topaz.vercel.app/games/pizzatower/index.html',
    'territorial io': 'https://k-web-topaz.vercel.app/games/territorialio/index.html',
    '1v1 lol': 'https://1v1-lol-online-github-io.vercel.app/file/',
    'ballistic chickens': 'https://k-web-topaz.vercel.app/games/ballisticchickens/index.html',
    'basketbros io': 'https://k-web-topaz.vercel.app/games/basketbrosio/index.html',
    'death run 3d': 'https://k-web-topaz.vercel.app/games/deathrun3d/index.html',
    'soccer random': 'https://k-web-topaz.vercel.app/games/soccerrandom/index.html',
    'sprinter': 'https://k-web-topaz.vercel.app/games/sprinter/index.html',
    'tron': 'https://k-web-topaz.vercel.app/games/tron/index.html',
    '1 on 1 soccer': 'https://k-web-topaz.vercel.app/games/1on1soccer/index.html',
    'bad time simulator': 'https://k-web-topaz.vercel.app/games/badtimesimulator/index.html',
    'amazing rope police': 'https://k-web-topaz.vercel.app/games/amazingropepolice/index.html',
    'celeste': 'https://k-web-topaz.vercel.app/games/celeste/index.html',
    'just fall lol': 'https://k-web-topaz.vercel.app/games/justfalllol/index.html',
    'ngon': 'https://k-web-topaz.vercel.app/games/ngon/index.html',
    'rocket soccer': 'https://k-web-topaz.vercel.app/games/rocketsoccer/index.html',
    'stick man climb': 'https://k-web-topaz.vercel.app/games/stickmanclimb/index.html',
    'osumania': 'https://k-web-topaz.vercel.app/games/osumania/index.html',
    'helix jump': 'https://k-web-topaz.vercel.app/games/helixjump/index.html',
    'dadish': 'https://k-web-topaz.vercel.app/games/dadish/index.html',
    'dadish 2': 'https://k-web-topaz.vercel.app/games/dadish2/index.html',
    'dadish 3': 'https://k-web-topaz.vercel.app/games/dadish3/index.html',
    'snow rider 3d': 'https://k-web-topaz.vercel.app/games/snowrider3d/index.html',
    'tube jumpers': 'https://k-web-topaz.vercel.app/games/tubejumpers/index.html',
    'yohoho': 'https://k-web-topaz.vercel.app/games/yohoho/index.html',
    '10 minutes till dawn': 'https://k-web-topaz.vercel.app/games/10minutestilldawn/index.html',
    'volley random': 'https://k-web-topaz.vercel.app/games/volleyrandom/index.html',
    'water works': 'https://k-web-topaz.vercel.app/games/waterworks/index.html',
    'geometry rash': 'https://k-web-topaz.vercel.app/games/geometryrash/index.html',
    'hole io': 'https://k-web-topaz.vercel.app/games/holeio/index.html',
    'sand trix': 'https://k-web-topaz.vercel.app/games/sandtrix/index.html',
    'shape shipper': 'https://k-web-topaz.vercel.app/games/shapeshipper/index.html',
    'slope ball': 'https://k-web-topaz.vercel.app/games/slopeball/index.html',
    'stickmang olf': 'https://k-web-topaz.vercel.app/games/stickmangolf/index.html',
    'tabs': 'https://k-web-topaz.vercel.app/games/tabs/index.html',
    'watermelon game': 'https://k-web-topaz.vercel.app/games/watermelongame/index.html',
    'wallsmash': 'https://k-web-topaz.vercel.app/games/wallsmash/index.html',
    'crimson fantasia': 'https://k-web-topaz.vercel.app/games/crimsonfantasia/index.html',
'final fantasy tactics advance': 'https://k-web-topaz.vercel.app/games/finalfantasytacticsadvance/index.html',
'drill dozer': 'https://k-web-topaz.vercel.app/games/drilldozer/index.html',
'advance wars dayo fruin': 'https://k-web-topaz.vercel.app/games/advancewarsdayofruin/index.html',
'castlevania dawn of sorrow': 'https://k-web-topaz.vercel.app/games/castlevaniadawnofsorrow/index.html',
'castlevania order of ecclesia': 'https://k-web-topaz.vercel.app/games/castlevaniaorderofecclesia/index.html',
'mario and luigi partners in time': 'https://k-web-topaz.vercel.app/games/marioandluigipartnersintime/index.html',
'comixzone': 'https://k-web-topaz.vercel.app/games/comixzone/index.html',
'ecco the dolphin': 'https://k-web-topaz.vercel.app/games/eccothedolphin/index.html',
'gun star heroes': 'https://k-web-topaz.vercel.app/games/gunstarheroes/index.html',
'phantasy star iv': 'https://k-web-topaz.vercel.app/games/phantasystariv/index.html',
'rangerx': 'https://k-web-topaz.vercel.app/games/rangerx/index.html',
'ristar': 'https://k-web-topaz.vercel.app/games/ristar/index.html',
'shining force': 'https://k-web-topaz.vercel.app/games/shiningforce/index.html',
'shinobi iii': 'https://k-web-topaz.vercel.app/games/shinobiiii/index.html',
'sonic the hedgehog': 'https://k-web-topaz.vercel.app/games/sonicthehedgehog/index.html',
'sonic the hedgehog2': 'https://k-web-topaz.vercel.app/games/sonicthehedgehog2/index.html',
'streets of rage 2': 'https://k-web-topaz.vercel.app/games/streetsofrage2/index.html',
'vectorman': 'https://k-web-topaz.vercel.app/games/vectorman/index.html',
'vectorman 2': 'https://k-web-topaz.vercel.app/games/vectorman2/index.html',
'illusion of gaia': 'https://k-web-topaz.vercel.app/games/illusionofgaia/index.html',
'pokemon yellow': 'https://k-web-topaz.vercel.app/games/pokemonyellow/index.html',
'abuda the alien': 'https://k-web-topaz.vercel.app/games/abudathealien/index.html',
'battle beavers': 'https://k-web-topaz.vercel.app/games/battlebeavers/index.html',
'control craft 2': 'https://k-web-topaz.vercel.app/games/controlcraft2/index.html',
'ageo f war': 'https://k-web-topaz.vercel.app/games/ageofwar/index.html',
'age of war 2': 'https://k-web-topaz.vercel.app/games/ageofwar2/index.html',
'amorphous': 'https://k-web-topaz.vercel.app/games/amorphous/index.html',
'bubble spinner': 'https://k-web-topaz.vercel.app/games/bubblespinner/index.html',
'crush the castle': 'https://k-web-topaz.vercel.app/games/crushthecastle/index.html',
'crush the castle 2': 'https://k-web-topaz.vercel.app/games/crushthecastle2/index.html',
'epic battle fantasy': 'https://k-web-topaz.vercel.app/games/epicbattlefantasy/index.html',
'epic battle fantasy 2': 'https://k-web-topaz.vercel.app/games/epicbattlefantasy2/index.html',
'epic battle fantasy 3': 'https://k-web-topaz.vercel.app/games/epicbattlefantasy3/index.html',
'fancy pants adventure 3': 'https://k-web-topaz.vercel.app/games/fancypantsadventure3/index.html',
'flood runner 2': 'https://k-web-topaz.vercel.app/games/floodrunner2/index.html',
'flood runner 3': 'https://k-web-topaz.vercel.app/games/floodrunner3/index.html',
'dragon boy 2': 'https://k-web-topaz.vercel.app/games/dragonboy2/index.html',
'neon rider': 'https://k-web-topaz.vercel.app/games/neonrider/index.html',
'pandemic 2': 'https://k-web-topaz.vercel.app/games/pandemic2/index.html',
'stick war': 'https://k-web-topaz.vercel.app/games/stickwar/index.html',
'stick war 2': 'https://k-web-topaz.vercel.app/games/stickwar2/index.html',
'ultimate flash sonic': 'https://k-web-topaz.vercel.app/games/ultimateflashsonic/index.html',
'zombocalypse': 'https://k-web-topaz.vercel.app/games/zombocalypse/index.html',
'zombotron': 'https://k-web-topaz.vercel.app/games/zombotron/index.html',
'zombotron 2': 'https://k-web-topaz.vercel.app/games/zombotron2/index.html',
'backrooms 2d': 'https://k-web-topaz.vercel.app/games/backrooms2d/index.html',
'basket random': 'https://k-web-topaz.vercel.app/games/basketrandom/index.html',
'csgo clicker': 'https://k-web-topaz.vercel.app/games/csgoclicker/index.html',
'doom': 'https://k-web-topaz.vercel.app/games/doom/index.html',
'funny shooter 2': 'https://k-web-topaz.vercel.app/games/funnyshooter2/index.html',
'gun fest': 'https://k-web-topaz.vercel.app/games/gunfest/index.html',
'infinite craft': 'https://k-web-topaz.vercel.app/games/infinitecraft/index.html',
'lows adventures 2': 'https://k-web-topaz.vercel.app/games/lowsadventures2/index.html',
'pako highway': 'https://k-web-topaz.vercel.app/games/pakohighway/index.html',
'recoil': 'https://k-web-topaz.vercel.app/games/recoil/index.html',
'run 3 plus': 'https://k-web-topaz.vercel.app/games/run3plus/index.html',
'slope city': 'https://k-web-topaz.vercel.app/games/slopecity/index.html',
'state io': 'https://k-web-topaz.vercel.app/games/stateio/index.html',
'sudoku': 'https://k-web-topaz.vercel.app/games/sudoku/index.html',
'superhero drop': 'https://k-web-topaz.vercel.app/games/superherodrop/index.html',
'balloon run': 'https://k-web-topaz.vercel.app/games/balloonrun/index.html',
'crazy tunnel 3d': 'https://k-web-topaz.vercel.app/games/crazytunnel3d/index.html',
'eagler 1.8': 'https://k-web-topaz.vercel.app/games/eagler1.8/index.html',
'geometry dash sky': 'https://k-web-topaz.vercel.app/games/geometrydashsky/index.html',
'wubzzys amazing adventure': 'https://k-web-topaz.vercel.app/games/wubzzysamazingadventure/index.html',
'gold digger frvr': 'https://k-web-topaz.vercel.app/games/golddiggerfrvr/index.html',
'hexgl': 'https://k-web-topaz.vercel.app/games/hexgl/index.html',
'house of hazards': 'https://k-web-topaz.vercel.app/games/houseofhazards/index.html',
'pickc rafter': 'https://k-web-topaz.vercel.app/games/pickcrafter/index.html',
'precision client': 'https://k-web-topaz.vercel.app/games/precisionclient/index.html',
'subway runner': 'https://k-web-topaz.vercel.app/games/subwayrunner/index.html',
'xx142-b2.exe': 'https://k-web-topaz.vercel.app/games/xx142-b2.exe/index.html',
'canopy': 'https://k-web-topaz.vercel.app/games/canopy/index.html',
'cave chaos': 'https://k-web-topaz.vercel.app/games/cavechaos/index.html',
'change type': 'https://k-web-topaz.vercel.app/games/changetype/index.html',
'cheese dreams': 'https://k-web-topaz.vercel.app/games/cheesedreams/index.html',
'chisel': 'https://k-web-topaz.vercel.app/games/chisel/index.html',
'chisel 2': 'https://k-web-topaz.vercel.app/games/chisel2/index.html',
'ditto': 'https://k-web-topaz.vercel.app/games/ditto/index.html',
'feed me': 'https://k-web-topaz.vercel.app/games/feedme/index.html',
'final ninja': 'https://k-web-topaz.vercel.app/games/finalninja/index.html',
'frost bite': 'https://k-web-topaz.vercel.app/games/frostbite/index.html',
'frost bite 2': 'https://k-web-topaz.vercel.app/games/frostbite2/index.html',
'ice breaker': 'https://k-web-topaz.vercel.app/games/icebreaker/index.html',
'mutiny': 'https://k-web-topaz.vercel.app/games/mutiny/index.html',
'nitrome must die': 'https://k-web-topaz.vercel.app/games/nitromemustdie/index.html',
'oodle gobs': 'https://k-web-topaz.vercel.app/games/oodlegobs/index.html',
'super treadmill': 'https://k-web-topaz.vercel.app/games/supertreadmill/index.html',
'swindler': 'https://k-web-topaz.vercel.app/games/swindler/index.html',
'test subject arena': 'https://k-web-topaz.vercel.app/games/testsubjectarena/index.html',
'test subject complete': 'https://k-web-topaz.vercel.app/games/testsubjectcomplete/index.html',
'twin shot': 'https://k-web-topaz.vercel.app/games/twinshot/index.html',
'twin shot 2': 'https://k-web-topaz.vercel.app/games/twinshot2/index.html',
'3 line': 'https://k-web-topaz.vercel.app/games/3line/index.html',
'bike champ': 'https://k-web-topaz.vercel.app/games/bikechamp/index.html',
'bike champ 2': 'https://k-web-topaz.vercel.app/games/bikechamp2/index.html',
'corporation inc': 'https://k-web-topaz.vercel.app/games/corporationinc/index.html',
'shop empire fable': 'https://k-web-topaz.vercel.app/games/shopempirefable/index.html',
'cactus mccoy': 'https://k-web-topaz.vercel.app/games/cactusmccoy/index.html',
'cactus mccoy 2': 'https://k-web-topaz.vercel.app/games/cactusmccoy2/index.html',
'papa louie': 'https://k-web-topaz.vercel.app/games/papalouie/index.html',
'papa louie 2': 'https://k-web-topaz.vercel.app/games/papalouie2/index.html',
'papa louie 3': 'https://k-web-topaz.vercel.app/games/papalouie3/index.html',
'steak and jake': 'https://k-web-topaz.vercel.app/games/steakandjake/index.html',
'steak and jake midnight march': 'https://k-web-topaz.vercel.app/games/steakandjakemidnightmarch/index.html',
    'goldeneye 007': 'https://k-web-topaz.vercel.app/games/goldeneye007/'
}